version: '3'
services:

  elasticsearch:
    restart: always
    image: reannz/elk_elasticsearch:latest
    container_name: elasticsearch
    env_file:
        - global-env.env
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    restart: always
    image: reannz/elk_logstash:latest
    container_name: logstash
    environment:
        # set to blank to enable debug - dump all events on logstash console
        LOGSTASH_DEBUG_DISABLE: "#"
    env_file:
        - elk.env
        - global-env.env
    ports:
        - "5043:5043"
    links:
        - "elasticsearch:elasticsearch"
    volumes:
        - logstash-data-6:/usr/share/logstash/data

  kibana:
    restart: always
    image: reannz/elk_kibana:latest
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      LOGGING_QUIET: "true"
    env_file:
        - elk.env
        - global-env.env
    links:
        - "elasticsearch:elasticsearch"

  apache:
    restart: always
    image: reannz/elk_apache:latest
    container_name: apache-elk
    environment:
        KIBANA_URL: http://kibana:5601/
        HTTPS_PORT: 9443
        HTTPD_ARGS: ""
        #HTTPD_ARGS: -DAPACHE_LOGS_STDOUT
    env_file:
        - elk.env
        - global-env.env
    ports:
        # temporarily use alt ports to avoid clash with admintool and icinga
        - "9080:80"
        - "9443:443"
    volumes:
        - apache-certs:/usr/local/apache2/conf/external
        - apache-logs:/usr/local/apache2/logs
    links:
        - "kibana:kibana"

volumes:
  # all volume names will get prefixed with the project name - "elk_"
  elasticsearch-data: {}
  logstash-data-6: {}
  apache-certs: {}
  apache-logs: {}
