version: '2'
services:

  elasticsearch:
    restart: always
    image: reannz/elk_elasticsearch:latest
    container_name: elasticsearch
    env_file:
        - global-env.env
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    restart: always
    image: reannz/elk_logstash:latest
    container_name: logstash
    env_file:
        - global-env.env
    ports:
        - "5043:5043"
    links:
        - "elasticsearch:elasticsearch"

  kibana:
    restart: always
    image: reannz/elk_kibana:latest
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    env_file:
        - global-env.env
    ports:
        - "5601:5601"
    links:
        - "elasticsearch:elasticsearch"

volumes:
  # all volume names will get prefixed with the project name - "elk_"
  elasticsearch-data: {}
