version: '2'
services:

  icingaweb:
    restart: always
    image: reannz/icinga_icingaweb:latest
    container_name: icingaweb
    env_file:
        - icinga.env
        - global-env.env
    ports:
        # temporarily use alt ports to avoid clash with admintool
        - "8080:80"
        - "8443:443"
    volumes:
        - icingaweb-apache-certs:/etc/apache2/certs
        - icingaweb-apache-logs:/var/log/apache2
        - icingaweb-logs:/var/log/icingaweb2
    volumes_from:
        # we need to see the Command Transport file
        - icinga
    links:
        - "postgres:postgres-icinga"

  icinga:
    restart: always
    image: reannz/icinga_icinga:latest
    container_name: icinga
    env_file:
        - icinga.env
        - global-env.env
    volumes:
        - icinga-external-conf:/etc/icinga2/conf.d/external
        - icinga-cmd:/var/run/icinga2
        - icinga-lib:/var/lib/icinga2
        - icinga-logs:/var/log/icinga2
    links:
        - "postgres:postgres-icinga"


  postgres:
    restart: always
    container_name: postgres-icinga
    image: reannz/icinga_postgres:latest
    env_file:
        - icinga.env
        - global-env.env
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  #  all volume names will get prefixed with the project name - "icinga_"
  icingaweb-apache-certs: {}
  icingaweb-apache-logs: {}
  icingaweb-logs: {}
  icinga-external-conf: {}
  icinga-cmd: {}
  icinga-lib: {}
  icinga-logs: {}
  postgres-data: {}
